[web]
    # Autorise l'accès aux fonctions (logs) sans authentification Cloud
    allow functions from = localhost 10.* 192.168.* 172.*
    
[api]
    # Permet d'exécuter des fonctions via l'API locale
    allow dashboard from = localhost 10.* 192.168.* 172.*